# Generated by Django 4.1 on 2022-09-28 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='profile',
            new_name='buyer_profile',
        ),
        migrations.AlterField(
            model_name='favourites',
            name='product_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='OnSale',
        ),
    ]
