# Generated by Django 4.1 on 2022-09-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_favourites_buyer_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='count',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='size',
        ),
    ]
