# Generated by Django 4.1 on 2022-09-23 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0.0)),
                ('product_description', models.TextField(help_text='Max symbols length is 400', max_length=400)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to=store.models.user_directory_path)),
                ('color', models.CharField(default='non-color', max_length=30)),
                ('category', models.CharField(choices=[('Hat', 'Hat'), ('Outwear', 'Outwear'), ('Shoes', 'Shoes'), ('Pants', 'Pants')], default='Outwear', max_length=100)),
                ('product_slug', models.SlugField(help_text='Use slug to define url name for your item', null=True, unique=True)),
                ('additional_information', models.CharField(help_text='Add some information if you want', max_length=500, null=True, verbose_name='Additional information')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutWear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0.0)),
                ('product_description', models.TextField(help_text='Max symbols length is 400', max_length=400)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to=store.models.user_directory_path)),
                ('color', models.CharField(default='non-color', max_length=30)),
                ('category', models.CharField(choices=[('Hat', 'Hat'), ('Outwear', 'Outwear'), ('Shoes', 'Shoes'), ('Pants', 'Pants')], default='Outwear', max_length=100)),
                ('product_slug', models.SlugField(help_text='Use slug to define url name for your item', null=True, unique=True)),
                ('additional_information', models.CharField(help_text='Add some information if you want', max_length=500, null=True, verbose_name='Additional information')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0.0)),
                ('product_description', models.TextField(help_text='Max symbols length is 400', max_length=400)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to=store.models.user_directory_path)),
                ('color', models.CharField(default='non-color', max_length=30)),
                ('category', models.CharField(choices=[('Hat', 'Hat'), ('Outwear', 'Outwear'), ('Shoes', 'Shoes'), ('Pants', 'Pants')], default='Outwear', max_length=100)),
                ('product_slug', models.SlugField(help_text='Use slug to define url name for your item', null=True, unique=True)),
                ('additional_information', models.CharField(help_text='Add some information if you want', max_length=500, null=True, verbose_name='Additional information')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0.0)),
                ('product_description', models.TextField(help_text='Max symbols length is 400', max_length=400)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to=store.models.user_directory_path)),
                ('color', models.CharField(default='non-color', max_length=30)),
                ('category', models.CharField(choices=[('Hat', 'Hat'), ('Outwear', 'Outwear'), ('Shoes', 'Shoes'), ('Pants', 'Pants')], default='Outwear', max_length=100)),
                ('product_slug', models.SlugField(help_text='Use slug to define url name for your item', null=True, unique=True)),
                ('additional_information', models.CharField(help_text='Add some information if you want', max_length=500, null=True, verbose_name='Additional information')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoesSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='Number of items per size')),
                ('size', models.CharField(choices=[('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('5.5', '5.5'), ('6.0', '6.0'), ('6.5', '6.5'), ('7.0', '7.0'), ('7.5', '7.5'), ('8.0', '8.0'), ('8.5', '8.5'), ('9.0', '9.0'), ('9.5', '9.5'), ('10.0', '10.0'), ('10.5', '10.5'), ('11.0', '11.0'), ('11.5', '11.5'), ('12.0', '12.0'), ('12.5', '12.5'), ('13.0', '13.0'), ('13.5', '13.5'), ('14.0', '14.0'), ('14.5', '14.5'), ('15.0', '15.0'), ('15.5', '15.5')], max_length=10)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shoes', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PantsSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='Number of items per size')),
                ('size', models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pants')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutWearSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='Number of items per size')),
                ('size', models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.outwear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HatSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='Number of items per size')),
                ('size', models.CharField(choices=[('ONE SIZE', '50-58')], max_length=10)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
