# Generated by Django 4.1 on 2022-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='is_on_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outwear',
            name='is_on_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pants',
            name='is_on_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='is_on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
